### ISSUE TITLE
How to train AT on ALDI？

### ISSUE THREAD

**Issue by Henryluoluoluo** [justinkay/aldi#13]
![Snipaste_2024-05-09_08-48-42](https://github.com/justinkay/aldi/assets/94333376/40e34191-858b-4369-8bd0-d28d14a24403)

**Comment by justinkay** [comment]
Thanks @Henryluoluoluo -- this is fixed by https://github.com/justinkay/aldi/commit/d4955eb5625e5d3aa5cdcd84b731edfba1fcf042.

Note however that AT does not use an EMA burn-in, so if you are trying to reproduce AT exactly you should burn in without EMA.

**Comment by Henryluoluoluo** [comment]
Thank you for your prompt response, I really appreciate it.
