### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by Henryluoluoluo** [justinkay/aldi#21]
Thank you for your nice work. When I run the Base-RCNN-FPN-Cityscapes_strongaug_ema.yaml in main branch, this error happened.
![bug](https://github.com/justinkay/aldi/assets/94333376/bb9ea896-175f-41ef-94a8-a12033b06496)

**Comment by justinkay** [comment]
Thanks @Henryluoluoluo - fixed by [13af8a8](https://github.com/justinkay/aldi/commit/13af8a834ca79b7eb60c9e943412bf23571e4708).
