### ISSUE TITLE
Error in Feature visualization

### ISSUE THREAD

**Issue by BalajiVenkatesan006** [justinkay/aldi#27]
After successfully training the models, I am trying to use this to visualize the feature space. but after a while the process is getting killed automatically. There is no clue in logs as well. Am I missing something ?

[08/13 16:52:22 d2.evaluation.evaluator]: Total inference pure compute time: 0:01:06 (0.020806 s / iter per device, on 1 devices)
Killed

**Comment by timmh** [comment]
This sounds to me like you might be running out of memory while the visualization script extracts image and proposal-level features. Could you try monitoring your memory consumption and possibly increase your swap space?

**Comment by justinkay** [comment]
Hi @BalajiVenkatesan006 closing this for now as it seems like an OOM issue. Let us know if you have further trouble and/or get it working.
