### ISSUE TITLE
Typo at the Table 3 (a)

### ISSUE THREAD

**Issue by sshhj89** [justinkay/aldi#29]
Hi, 

I think the source-only model AP50 should be "59.1" like other ablation study result.
By the way, I would like to use the best model. 
Will you share the best model soon?

**Comment by justinkay** [comment]
Hi @sshhj89, thank you for your interest.

Actually, this is a different source-only model than the one used by ALDI++. It is trained without strong augmentations and EMA, i.e. according to the base settings for the ablations in Table 2. Its performance is indeed 51.9.

Sure, I am happy to share the best model if that is useful for you. I will tag you when it's uploaded!

**Comment by justinkay** [comment]
Hi @sshhj89 , FYI final models are also available now in the [model zoo](https://github.com/justinkay/aldi/blob/main/docs/MODELS.md).
