### ISSUE TITLE
Feature Alignment module

### ISSUE THREAD

**Issue by helia-mohamadi** [justinkay/aldi#36]
Hello @justinkay, 
In your paper, you mentioned that you used a 'feature alignment algorithm' to adapt the source and target features in student. 
I reviewed your code, and I was wondering how can I enable and use feature alignment module in student part of ALDI-Best Config in ALDI++ framework, like knowledge distillation module in teacher part? 
Thank you

**Comment by justinkay** [comment]
Hi @helia-mohamadi, you can enable this feature by setting this value to True in your config file:

https://github.com/justinkay/aldi/blob/d07589dac71520264bd8a094531c1972035e0712/aldi/config.py#L39

**Comment by helia-mohamadi** [comment]
Tank you.

**Comment by helia-mohamadi** [comment]
Thank you.
