### ISSUE TITLE
Wrong _BASE_ in two config files

### ISSUE THREAD

**Issue by omid-reza** [justinkay/aldi#37]
Hi.

In two of the `_BASE_` address of the config files are wrong. The files are the below ones:

- [configs/cityscapes/OracleT-RCNN-FPN-Cityscapes_strongaug_ema.yaml](https://github.com/justinkay/aldi/blob/main/configs/cityscapes/OracleT-RCNN-FPN-Cityscapes_strongaug_ema.yaml)
- [configs/cityscapes/OracleT-RCNN-VitDetB-Cityscapes_strongaug_ema.yaml](https://github.com/justinkay/aldi/blob/main/configs/cityscapes/OracleT-RCNN-VitDetB-Cityscapes_strongaug_ema.yaml)

I think that they should be changed to the base config files.

Thanks.

**Comment by justinkay** [comment]
Thanks @omid-reza , but I think these are correct - they are meant to reference the Cityscapes-specific Base configs, which in turn reference the generic Base configs.

Please let me know if this is giving you any problems though.
