### ISSUE TITLE
Coefficient Loss Functions

### ISSUE THREAD

**Issue by helia-mohamadi** [justinkay/aldi#38]
Hello, @justinkay 
I wanted to know if I want to reduce the coefficient and the effect of alignment or distillation loss, how can I change that?

**Comment by justinkay** [comment]
For alignment, the image level weight is:

https://github.com/justinkay/aldi/blob/d07589dac71520264bd8a094531c1972035e0712/aldi/config.py#L41

and the instance (box) level weight is:

https://github.com/justinkay/aldi/blob/d07589dac71520264bd8a094531c1972035e0712/aldi/config.py#L45

For distillation, you would need to implement this yourself in a similar fashion.

**Comment by helia-mohamadi** [comment]
Thank you

**Comment by helia-mohamadi** [comment]
Hello again @justinkay,
I have one more question. 
I have trained the model several times, but the accuracy of the second phase test is less than the first phase. I trained the model with lr = 0.01 and my accuracy was 62.77 for the first phase and 43.63 for the second phase.
I also trained the model with lr = 0.001 and my accuracy was 65.5 for the first phase and 59.7 for the second phase. 
Do you know why this happened and in the second phase, despite the fact that domain adaptation was done, the accuracy was reduced?

**Comment by helia-mohamadi** [comment]
Hello again @justinkay, I have one more question.
I have trained the model several times, but the accuracy of the second phase test is less than the first phase. I trained the model with lr = 0.01 and my accuracy was 62.77 for the first phase and 43.63 for the second phase.
I also trained the model with lr = 0.001 and my accuracy was 65.5 for the first phase and 59.7 for the second phase.
Do you know why this happened and in the second phase, despite the fact that domain adaptation was done, the accuracy was reduced?
