### ISSUE TITLE
model weights in the Base-RCNN-FPN.yaml file

### ISSUE THREAD

**Issue by nieve01** [justinkay/aldi#42]
Hi, Dr.Kay, thanks for your graet work! 
This is my first time to learn domain adaptation and detectron2. I found that the model weights in the Base-RCNN-FPN.yaml file are models/model_final_f10217.pkl and the model in the download link you provided is model_final_280758.pkl. Are the weights of these two models the same?

**Comment by justinkay** [comment]
Hi @nieve01, nice find, this was a typo in the README. The correct model is indeed model_final_f10217.pkl. I've fixed the README. Thank you for pointing this out!
