### ISSUE TITLE
Evaluation Problems During Training

### ISSUE THREAD

**Issue by 455171668** [justinkay/aldi#43]
Hi,
Thank you for your research and I really like your achievement and sharing.
I use configs/cityscapes/Base-RCNN-FPN-Cityscapes_strongaug_ema.yaml to train, and perform evaluate after every 500 iterations. I encounter a problem that each time evaluate is performed 4 times, and the performance of the first 2 times and the last 2 times is quite different. Can you explain the reason? Thanks

[log.txt](https://github.com/user-attachments/files/17848423/log.txt)

**Comment by justinkay** [comment]
Both the student and teacher model will be evaluated on each test set in your config file. From your log:
```
TEST:
  - cityscapes_val
  - cityscapes_foggy_val
 ```

So your 4 evaluations are:
1. cityscapes_val - student
2. cityscapes_val - teacher
3. cityscapes_foggy_val - student
4. cityscapes_foggy_val - teacher

Hope this clarifies!

**Comment by 455171668** [comment]
Thank you for your reply。
I use configs/cityscapes/Base-RCNN-FPN-Cityscapes_strongaug_ema.yaml to train. Does EMA also enable the teacher student framework for baseline training?
I see that the baseline configuration does not use the target dataset. Can you explain in detail how EMA training is used in the baseline?Thanks
