### ISSUE TITLE
question about how to set num_worker and batchsize？

### ISSUE THREAD

**Issue by nieve01** [justinkay/aldi#44]
Hi Justin, thank you for your valuable work.
I encountered some problems when training your model. This is my first time to use the server for training. I have an 80GB A800. At first, I used the default.yaml to train the model, and it gave an error when num_worker=4. Then I set num_worker to 0, and the batchsize was still 48. Then I ran the nvidia-smi command and found that my gpu utilization was only 20% at most, and sometimes it was 0. 
Maybe you can tell me how to set num_worker and batchsize? Thank you very much for your work.

**Comment by justinkay** [comment]
Hey @nieve01, `num_workers` has to do with processes of the PyTroch DataLoader which does not affect the batch size and so won't affect your GPU utilization. `num_workers` should be set based on your number of CPU cores. if you'd like to adjust the batch size (increasing your GPU utilization), you can use the  `SOLVER.IMS_PER_BATCH` config variable, see here: https://github.com/justinkay/aldi/blob/c1b8f27b9c186c47336be8f391acd59a6a3140e1/configs/Base-RCNN-FPN.yaml#L15
