### ISSUE TITLE
Confusion about the soft distillation

### ISSUE THREAD

**Issue by nieve01** [justinkay/aldi#46]
Hello again @justinkay ，I am confused about the distillation part. Distillation is divided into two parts, one is RPN and the other is ROI.
(1) The output of RPN is ① objectness predictions ② regression predictions. For example, suppose the RPN network generates 20,000 proposals. When training the RPN network, 256 samples are randomly sampled (positive and negative samples 1:1). We need to ensure that the 256 samples sampled by teacher and student are the same, and then calculate the cross entropy loss of the objectness predictions of the 256 positive and negative samples (the teacher's objectness predictions are post-processed with sigmoid), and calculate the regression loss.
(2) ROI, first of all, we need to ensure that the proposals input by the ROI of the teacher and the student are the same, so directly copy the proposal selected by the student to the teacher, and then calculate the classification loss and regression loss.
I don't know if my understanding is correct. If there is any mistake, can you point it out?

**Comment by justinkay** [comment]
Yes, your understanding sounds correct to me!

**Comment by nieve01** [comment]
thank you!
