### ISSUE TITLE
Changing the backbone for smaller datasets

### ISSUE THREAD

**Issue by omid-reza** [justinkay/aldi#47]
Hi,

Hope you are well. I am writing to inquire that is it possible to change the backbone to Faster R-CNN for smaller datastes? If yes, Can you hint for the way the it can be done?

Thanks.

**Comment by justinkay** [comment]
Hi @omid-reza, we've built upon Detectron2, so you can add new backbones in the same way: https://detectron2.readthedocs.io/en/stable/tutorials/write-models.html

You can check our implementation of VGG-16 in the `extras` branch for an example: https://github.com/justinkay/aldi/blob/extras/aldi/backbone.py

**Comment by omid-reza** [comment]
Thanks. I have another question, How can i change epoch number and batch size? Can it be done in config files?

**Comment by justinkay** [comment]
The typical process is: register a backbone class with Detectron2 using `@BACKBONE_REGISTRY.register()`, then you can instantiate this backbone by referencing it in the config file like so:
https://github.com/justinkay/aldi/blob/7764ba2b13408b4650e5156dcabd5b2b5123a38d/configs/cityscapes/Base-RCNN-VGG-Cityscapes.yaml#L7

**Comment by omid-reza** [comment]
Thanks. Can we also use pretrained weights for VGG by adding config like : "WEIGHTS": "models/model_final_84107b.pkl"? Should anything be changed for have pretrained weight in it? Thanks for your great support.
