### ISSUE TITLE
How to save augmented images?

### ISSUE THREAD

**Issue by DenisN03** [justinkay/aldi#48]
I have synthetic data with a different domain from the target domain. In this case the domains are similar to Sim10k → Cityscapes. Can you please tell me if the original images can be converted and saved using Sim10k → Cityscapes weights? I plan to use the augmented images in training.

**Comment by justinkay** [comment]
Hi @DenisN03, I'm not sure I understand. What are you hoping the saved images would look like? Which augmentations do you want to save?

**Comment by justinkay** [comment]
Hi @DenisN03 this project is for adapting object detection models, so no this is not the primary use. You can look into image to image translation techniques like CycleGAN, which one of our baselines (UMT) uses.
