### ISSUE TITLE
Config for ALDI VGG

### ISSUE THREAD

**Issue by omid-reza** [justinkay/aldi#49]
Hi,

I could not found the config for ALDI with VGG architecture. Is it available or one should write it on their own?

Thanks!

**Comment by justinkay** [comment]
Hi @omid-reza , these are on the `extras` branch, e.g.: 

https://github.com/justinkay/aldi/blob/extras/configs/cityscapes/Base-RCNN-VGG-Cityscapes.yaml

**Comment by omid-reza** [comment]
This is a base config. Is there any ALDI Config file for VGG? Thanks.

**Comment by justinkay** [comment]
Currently no, but you should easily be able to do this by changing this line:

https://github.com/justinkay/aldi/blob/7764ba2b13408b4650e5156dcabd5b2b5123a38d/configs/cityscapes/ALDI-Best-Cityscapes.yaml#L1

To reference the VGG base config instead (and then updating the path to the pre-trained weights as well)
