### ISSUE TITLE
there is no documentation about inference after the domain adaption is done. 

### ISSUE THREAD

**Issue by BalajiVenkatesan006** [justinkay/aldi#8]
It would be good, if there is a documentation for the inference.

**Comment by justinkay** [comment]
Thanks for the suggestion, we will add this! In the meantime, the short answer is that inference is done exactly the same way as any other model Detectron2.

**Comment by justinkay** [comment]
This has been added to the readme: https://github.com/justinkay/aldi/blob/main/docs/TRAINING.md

For further deployment info, see the Detectron2 deployment docs: https://detectron2.readthedocs.io/en/latest/tutorials/deployment.html
